const dummyData = {
  gallery: [
    { src: "/assets/gallery/gall1.webp", alt: "Gallery Photo 1" },
    { src: "/assets/gallery/gall2.webp", alt: "Gallery Photo 2" },
    { src: "/assets/gallery/gall3.webp", alt: "Gallery Photo 3" },
    { src: "/assets/gallery/gall4.webp", alt: "Gallery Photo 4" },
    { src: "/assets/gallery/gall5.webp", alt: "Gallery Photo 5" },
    { src: "/assets/gallery/gall6.webp", alt: "Gallery Photo 6" },
    { src: "/assets/gallery/gall7.webp", alt: "Gallery Photo 7" },
    { src: "/assets/gallery/gall8.webp", alt: "Gallery Photo 8" },
    { src: "/assets/gallery/gall9.webp", alt: "Gallery Photo 9" },
    { src: "/assets/gallery/gall10.webp", alt: "Gallery Photo 10" },
    { src: "/assets/gallery/gall11.webp", alt: "Gallery Photo 11" },
    { src: "/assets/gallery/gall12.webp", alt: "Gallery Photo 12" },
    { src: "/assets/gallery/gall13.webp", alt: "Gallery Photo 13" },
    { src: "/assets/gallery/gall14.webp", alt: "Gallery Photo 14" },
    // { src: "/assets/gallery/gall15.webp", alt: "Gallery Photo 15" },
  ],
  documentation: [
    {
      id: 1,
      title: "Certificate / Document 1",
      description: "Add your certificate or documentation description here.",
      icon: "ri-award-line",
      image: null, // Change to: "/assets/docs/cert1.webp"
      link: null, // Change to: "https://link-to-certificate.com"
      delay: "100",
    },
    {
      id: 2,
      title: "Certificate / Document 2",
      description: "Add your certificate or documentation description here.",
      icon: "ri-file-text-line",
      image: null,
      link: null,
      delay: "200",
    },
    {
      id: 3,
      title: "Certificate / Document 3",
      description: "Add your certificate or documentation description here.",
      icon: "ri-medal-line",
      image: null,
      link: null,
      delay: "300",
    },
    {
      id: 4,
      title: "Certificate / Document 4",
      description: "Add your certificate or documentation description here.",
      icon: "ri-bookmark-line",
      image: null,
      link: null,
      delay: "400",
    },
    {
      id: 5,
      title: "Certificate / Document 5",
      description: "Add your certificate or documentation description here.",
      icon: "ri-shield-star-line",
      image: null,
      link: null,
      delay: "500",
    },
    {
      id: 6,
      title: "Certificate / Document 6",
      description: "Add your certificate or documentation description here.",
      icon: "ri-graduation-cap-line",
      image: null,
      link: null,
      delay: "600",
    },
  ],
};

export default dummyData;
